### ISSUE TITLE
Song doesn't start playing

### ISSUE THREAD

**Issue by Kuuhhl** [j0hnk1m/typenvibe#2]
First of all, let me tell you I'm really excited about this project!
I was looking for a music-game to improve at touch-typing and this seems very promising.

However, I had problems getting the game to run.
I don't know why, but the song doesn't start to play after the countdown-timer is up. 
The text just starts changing and I don't hear the lyrics.
Did I set it up wrong?
What I did:
- Login with Spotify
- Close Spotify client on PC so that it doesn't interfere
- Choose a song and start it

My browser has audio enabled so I'm not sure what might be the problem.
Let me know if you need any further info.

**Comment by j0hnk1m** [comment]
Hmm. I haven't updated the site in a while because of school, but I just tried it and it should still work. Closing the spotify client on PC shouldn't have anything to do with it. I believe this only works if you have Spotify Premium since it's coded to play a specific full-length track.

**Comment by Kuuhhl** [comment]
I looked into it and you are right. In the Web-API [docs](https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/) they write:
> With Connect Web API you can only control Spotify Premium users’ playback.

You could maybe add it to the readme so that everyone knows they have to have Spotify Premium.
